---
language: node_js
node_js:
  - "7"

sudo: false

addons:
  postgresql: "9.3"

services:
  - postgresql

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_DATABASE=travis_ci_test
    - DB_USER=postgres

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm run migrate

before_install:
  - npm config set spin false
  - npm install -g yarn

install:
  - yarn

script:
  - npm test
