---
language: node_js
node_js:
  - "7"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g yarn

install:
  - yarn

script:
  - npm test
